version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: fiap-tech-challenge-fase-4-products-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: products
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - fiap

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-tech-challenge-fase-4-products
    ports:
      - "3000:3000"
    environment:
      # Update these to match how your application reads its Mongo config.
      # For example, if your code uses a connection string, you could do:
      - PORT=3000
      - MONGO_URL=mongodb://root:example@db:27017
    networks:
      - fiap

networks:
  fiap:
    driver: bridge
