apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-products-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lanchonete-products-api
  template:
    metadata:
      labels:
        app: lanchonete-products-api
    spec:
      containers:
        - name: lanchonete-products-api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: PORT
              value: "{{ .Values.api.env.PORT }}"
            - name: MONGO_URL
              value: "{{ .Values.api.env.MONGO_URL }}"
